### ISSUE TITLE
Issue with XCMS MSnbase readMSData tool

### ISSUE THREAD

**Issue by thcontini1** [CESNET/usegalaxy#41]
Hi, 
I want to use XCMS workflow on GALAXY and had some issue with the tool _MSnbase readMSData_. 
Here is the error message: 
![image](https://github.com/user-attachments/assets/639e152d-f409-40cf-8996-a86108a35698)

Imported files are in format mzml. 
I tried with single dataset and dataset collection and the issue was the same. 

Thank you for your help.

**Comment by martindemko** [comment]
Hi,
unfortunately, the tool is not optimized for our type of infrastructure (i.e., using Pulsar as middleware). It does not specify <required_files> in the tool XML configuration file. Therefore, one of the needed source files (lib.r) was not transferred and could not be used. I fixed the tool XML file and restarted your job and it finished successfully. However, the fix is only local and would need to be maintained in the repo in the Toolshed. I will question other admins on how to proceed. The best would be to fix the tool globally but I'm not the owner of the repository.

Best,
Martin

**Comment by martindemko** [comment]
So,
I found the original GitHub repo and wrote the issue there. Now, the question is if somebody will fix it. I'm closing the issue.

**Comment by martenson** [comment]
Please crosspost the link to that issue here.

**Comment by martindemko** [comment]
https://github.com/workflow4metabolomics/tools-metabolomics/issues/279

**Comment by martindemko** [comment]
Hi @thcontini1, I totally missed this conversation; the notification from GitHub ended up in SPAM.
